version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - copyloopvar
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - whitespace
#    - exhaustive
#    - godot
#    - cyclop
#    - dupl
#    - durationcheck
#    - errname
#    - errorlint
#    - exhaustivestruct
#    - forbidigo
#    - forcetypeassert
#    - funlen
#    - gochecknoglobals
#    - gochecknoinits
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
#    - godox
#    - goerr113
#    - gofumpt
#    - golint
#    - gomnd
#    - gomoddirectives
#    - gosec (gas)
#    - gosimple (megacheck)
#    - ifshort
#    - importas
#    - interfacer
#    - lll
#    - makezero
#    - maligned
#    - nestif
#    - nilerr
#    - nlreturn
#    - noctx
#    - paralleltest
#    - predeclared
#    - promlinter
#    - revive
#    - scopelint
#    - sqlclosecheck
#    - tagliatelle
#    - testpackage
#    - thelper
#    - tparallel
#    - unparam
#    - wastedassign
#    - wrapcheck
#    - wsl
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: strict
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - golang.org/x/crypto/argon2

formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
      no-inline-comments: true
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
